version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: annotation-db
    environment:
      POSTGRES_DB: annotation_tool
      POSTGRES_USER: annotation_user
      POSTGRES_PASSWORD: annotation_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - annotation-network

  # Java Spring Boot Backend
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: annotation-backend
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/annotation_tool
      - SPRING_DATASOURCE_USERNAME=annotation_user
      - SPRING_DATASOURCE_PASSWORD=annotation_password
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ./uploads:/app/uploads
    networks:
      - annotation-network

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: annotation-frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:8080/api
    depends_on:
      - backend
    networks:
      - annotation-network

volumes:
  postgres_data:

networks:
  annotation-network:
    driver: bridge
